### PR TITLE
IWCE--4--Created category view

### PR DESCRIPTION
**Pull request by veronikaTailored**

### CODE REVIEW

**Comment by gunjanpatel** [comment]
`IWCE--4--` is not valid issue key.

**Comment by gunjanpatel** [comment]
Also `IWCE--4--Create_category_view_and_relate_with_task` is very long branch name and not valid. It should be just a issue key. Isn't I wrote it clearly in task?

**Comment by veronikaTailored** [comment]
Ok..Only write like "IWCE - 4 "?

**Comment by gunjanpatel** [comment]
`IWCE - 4` is still not valid. It should be `IWCE-4` (without space). 
Do you see space here in key?
issue-key

**Pull request closed without merging**
